### ISSUE TITLE
MalformedInputException when calling sbt migrate

### ISSUE THREAD

**Issue by davidnadeau** [inoio/sbt-pillar-plugin#16]
I successfully call sbt createKeyspace, and the keyspace and migration table get created. However when calling sbt migrate, i get a malformed input exception. I have only 1 migration file in the `my-project/src/main/resources/migrations` dir:
```
-- description: creates events table
-- authoredAt: 1370023262
-- up:

CREATE TABLE events (
  batch_id text,
  occurred_at uuid,
  event_type text,
  payload blob,
  PRIMARY KEY (batch_id, occurred_at, event_type)
)
```
my application.conf:
```
pillar {
  connectionString           = "cassandra://127.0.0.1:9042/my_keyspace"
  replicationFactorConfigKey = 1
  defaultConsistencyLevel    = "ONE"
}
```
my build.sbt
```
lazy val pillarSettings = sbtpillar.Plugin.pillarSettings ++ Seq(
  pillarConfigFile                       := file("my-project/src/main/resources/application.conf"),
  pillarConfigKey                        := "pillar.connectionString",
  pillarReplicationFactorConfigKey       := "pillar.replicationFactor",
  pillarDefaultConsistencyLevelConfigKey := "pillar.defaultConsistencyLevel",
  pillarMigrationsDir                    := file("my-project/src/main/resources/migrations")
)
```

For example here is the output calling sbt migrate:
```
[info] Reading config from my-project/src/main/resources/application.conf
[info] Migrating keyspace my_keyspace at 127.0.0.1:9042 using migrations in [my-project/src/main/resources/migrations] with consistency ONE
[error] An error occurred while performing task: java.nio.charset.MalformedInputException: Input length = 1
java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:67)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at de.kaufhof.pillar.Parser.parse(Parser.scala:56)
	at io.ino.sbtpillar.Plugin$Pillar$$anonfun$io$ino$sbtpillar$Plugin$Pillar$$loadMigrations$1.apply(Plugin.scala:228)
	at io.ino.sbtpillar.Plugin$Pillar$$anonfun$io$ino$sbtpillar$Plugin$Pillar$$loadMigrations$1.apply(Plugin.scala:225)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at io.ino.sbtpillar.Plugin$Pillar$.io$ino$sbtpillar$Plugin$Pillar$$loadMigrations(Plugin.scala:225)
	at io.ino.sbtpillar.Plugin$Pillar$$anonfun$9.apply(Plugin.scala:192)
	at io.ino.sbtpillar.Plugin$Pillar$$anonfun$9.apply(Plugin.scala:192)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at io.ino.sbtpillar.Plugin$Pillar$.migrate(Plugin.scala:192)
	at io.ino.sbtpillar.Plugin$$anonfun$taskSettings$4$$anonfun$apply$7$$anonfun$apply$8.apply(Plugin.scala:81)
	at io.ino.sbtpillar.Plugin$$anonfun$taskSettings$4$$anonfun$apply$7$$anonfun$apply$8.apply(Plugin.scala:69)
	at io.ino.sbtpillar.Plugin$Pillar$.withSession(Plugin.scala:158)
	at io.ino.sbtpillar.Plugin$$anonfun$taskSettings$4$$anonfun$apply$7.apply(Plugin.scala:69)
	at io.ino.sbtpillar.Plugin$$anonfun$taskSettings$4$$anonfun$apply$7.apply(Plugin.scala:66)
	at io.ino.sbtpillar.Plugin$Pillar$.withCassandraUrl(Plugin.scala:131)
	at io.ino.sbtpillar.Plugin$$anonfun$taskSettings$4.apply(Plugin.scala:66)
	at io.ino.sbtpillar.Plugin$$anonfun$taskSettings$4.apply(Plugin.scala:62)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by el-dom** [comment]
Wild guess, but does your migration file contain a byte order mark? That could cause parse errors.

**Comment by davidnadeau** [comment]
it does not

**Comment by davidnadeau** [comment]
I moved my folder to the conf/migrations directory, and it works now. It may be an issue with the custom  migration folder setting.

**Comment by davidnadeau** [comment]
reopening.

When I create the directory and run sbt migrate, the migration succeeds. When I pull the code from github and run sbt migrate, I get a MalformedInputException. I then need to delete and recreate the directory, and the migrations work again. Any ideas?

**Comment by magro** [comment]
So you get the excepting when there's the .DS_Store file, and you don't get the exception when this file does not exist?

As you say, probably we can exclude .DS_Store files statically, assuming that nobody stores migrations in such a file.
Do you want to submit a pull request for this?

**Comment by davidnadeau** [comment]
It will be a pr in the https://github.com/Galeria-Kaufhof/pillar repo, since its has to be solved in the `Registry` object where the directory is parsed.

**Comment by davidnadeau** [comment]
Also, if the migration dir has any dotfiles, the migrations will fail with `java.nio.charset.MalformedInputException: Input length = 1`.

All dotfiles need to be ignore when reading the dir.

**Comment by magro** [comment]
What about https://github.com/inoio/sbt-pillar-plugin/blob/master/src/main/scala/io/ino/sbtpillar/Plugin.scala#L223?

**Comment by davidnadeau** [comment]
that works, i've added a pr and some tests.
